x-airflow-common: &airflow-common
  build: .
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    ANALYTICS_DB_HOST: ${ANALYTICS_DB_HOST}
    ANALYTICS_DB_PORT: ${ANALYTICS_DB_PORT}
    ANALYTICS_DB_NAME: ${ANALYTICS_DB_NAME}
    ANALYTICS_DB_USER: ${ANALYTICS_DB_USER}
    ANALYTICS_DB_PASSWORD: ${ANALYTICS_DB_PASSWORD}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./etl:/opt/airflow/etl
    - ./data:/opt/airflow/data
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  analytics_db:
    image: postgres:13
    environment:
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_pass
      POSTGRES_DB: analytics_db
    ports:
      - "5433:5432"
    volumes:
      - analytics_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "analytics_user"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
        airflow connections add analytics_db --conn-type postgres --conn-host ${ANALYTICS_DB_HOST} --conn-login ${ANALYTICS_DB_USER} --conn-password ${ANALYTICS_DB_PASSWORD} --conn-schema ${ANALYTICS_DB_NAME} --conn-port ${ANALYTICS_DB_PORT} || true &&
        airflow variables set batch_size 5000 &&
        airflow variables set fuentes_activas csv1,csv2
      "

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    restart: always

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: always

volumes:
  postgres_data:
  analytics_db_data:
